[dependencies]
base = "0.13.2"
array = "https://github.com/aviate-labs/array.mo#v0.2.0@863a668bcbb3c3799a62c36b2cba2c32d1fcc433"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main@4781cb03efd34b124c22396c69710b374366c797"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0@1af0e8814bac5ca7ed23a6c094204b46d9056c2e"
xtended-numbers = "0.3.1"
itertools = "0.2.2"
icrc1 = "https://github.com/NatLabs/icrc1#master@0800c7ac03026a4c5a72eeb357cbbd0aca2f0fb4"

[package]
name = "icrc1"
version = "0.1.0"
description = "icrc1"
repository = "https://github.com/NatLabs/icrc1"